### ISSUE TITLE
Timeseries API - Make 404 responses consistent on /query/data/latest

### ISSUE THREAD

**Issue by hekka** [equinor/OmniaPlant#6] opened 2023-09-26 12:51 UTC
**Describe the bug**
When querying data in batches on tags that (I think) I dont have access to I get a nice response that says which tags are 404 (not 403 but fair enough..) See screenshot 1.
This is nice since I still get data for tags that are valid and accessible

But when I send in a batch with invalid tag names, the whole batch fails, even for valid tags (see screenshot 2) This makes me lose the whole batch and

**Trace ID**
    "traceId": "0HMT7I3PQEH7M:00000DB3"

**To Reproduce**
/query/data/latest?federationSource=IMS

```json
[
    {
        "facility": "1219",
        "name":"1219-23PST0502_X",
          "endTime": "2023-09-01T05:00:00Z"
    },
    {
        "facility": "1219",
        "name":"1219-23PT0504_X",
        "endTime": "2023-09-01T05:00:00Z"
    },
     {
        "facility": "1219",
        "name":"GFA1110-23PT0504_X",
        "endTime": "2023-09-01T05:00:00Z"
    }

]
```

**Expected behavior**
I would like both requests to give the same format of error output, so that the whole batch does not get lost as in screenshot 2.

**Screenshots**
![Screenshot1](https://github.com/equinor/OmniaPlant/assets/2461675/bac06a69-5f11-41ac-b3da-36b77513d822) Screenshot 1

<img width="1134" alt="image" src="https://github.com/equinor/OmniaPlant/assets/2461675/b7f39d55-3be3-4bad-8f2f-0ac764272623"> Screenshot 2

**Criticality**
Low/Medium

**Comment by eaidland** [comment] 2023-09-27 11:13
The 404 response is by design.

Please try again with the query to check that the response should be fixed.

**Closed as completed by eaidland** 2023-09-27 11:13 UTC

**Comment by hekka** [comment] 2023-09-27 11:18
The 404 response is good, the main gripe is with the 400 response which throws away all good data as well.

**Comment by eaidland** [comment] 2023-09-27 13:08
We have change this behavior and recreated the same response.

**Comment by hekka** [comment] 2023-09-27 13:31
Thank you for the clarification, I tried it again and see wanted the behaviour. 

Br,
Henri
